fix workflow

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -33,6 +33,15 @@ jobs:
           # Substitui o placeholder __IMAGE_TAG__ pela hash do commit
           sed -i "s|__IMAGE_TAG__|${{ github.sha }}|" deployment-app.yaml
 
+                    # Substitui o placeholder
+          sed -i "s|__IMAGE_TAG__|${{ github.sha }}|" deployment-app.yaml
+
+          # Evita push se __IMAGE_TAG__ não foi substituído
+          if grep -q "__IMAGE_TAG__" deployment-app.yaml; then
+            echo "❌ ERRO: placeholder __IMAGE_TAG__ ainda presente. Abortando push para o GitOps!"
+            exit 1
+          fi
+          
           git add deployment-app.yaml
           git commit -m "Atualiza imagem giropops-senhas para ${{ github.sha }}"
           git push origin main
